name: Build and Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Pull latest code
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          cd /root/ANTIGRAVITY/honkingversion
          git pull origin master
          echo "✅ Code pulled successfully"
          EOF

      - name: Rebuild and restart services
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          cd /root/ANTIGRAVITY/honkingversion
          docker compose down
          docker compose pull
          docker compose up -d --build
          echo "✅ Services restarted"
          EOF

      - name: Wait for services
        run: sleep 30

      - name: Verify deployment
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          cd /root/ANTIGRAVITY/honkingversion
          echo "Service status:"
          docker compose ps
          EOF

      - name: Health check - API
        run: |
          echo "Checking API health..."
          curl -s https://api.honkingversion.runfoo.run/ | grep -q "Welcome" && echo "✅ API is responding" || echo "⚠️  API health check failed"

      - name: Health check - Web
        run: |
          echo "Checking Web health..."
          curl -s https://honkingversion.runfoo.run/ | grep -q "HONKINGVERSION" && echo "✅ Web is responding" || echo "⚠️  Web health check failed"

      - name: Cleanup
        run: |
          rm -f ~/.ssh/deploy_key
